# Generated by Django 3.1.12 on 2025-01-04 09:22

import bson.objectid
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, editable=False, primary_key=True, serialize=False)),
                ('question_name', models.CharField(max_length=50)),
                ('question_desc', models.TextField(max_length=500)),
                ('visible_test_cases', djongo.models.fields.JSONField(default=list)),
                ('hidden_test_cases', djongo.models.fields.JSONField(default=list)),
            ],
        ),
    ]
